name: ekarma
description: "App for Finding Part Time Job"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.0
  geolocator: any
  get_it: ^7.6.2
  go_router: ^10.1.2
  google_maps_flutter: ^2.5.0
  google_maps_webservice: any
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  location: ^5.0.3
  permission_handler: ^10.4.5
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  responsive_sizer: ^3.2.0
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.4
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/logo/yalla_gai_logo.jpg"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/logo/
    - assets/images/images/
    - assets/images/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-VariableFont_wght.ttf

    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-VariableFont_wght.ttf